Revert "Bump the koin group with 3 updates (#1813)"
org.koin.core.error.KoinAppAlreadyStartedException: A Koin Application has already been started

This reverts commit 6bd5dc73a55eee5d471cb5712c78f16dc11539f1.